# This YAML file contains driver-registrar & csi driver nodeplugin API objects
# that are necessary to run CSI nodeplugin for H3

{{- $csiH3Properties := merge .Values $.Values.global}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-h3
  labels:
  {{- include "common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-h3
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app: csi-nodeplugin-h3
    spec:
      {{- if or (.Values.dockerRegistrySecret) (.Values.global.dockerRegistrySecret) }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecret | default .Values.global.dockerRegistrySecret }}
      {{- end}}
      serviceAccountName: csi-nodeplugin-h3
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: node-driver-registrar
          {{- with $csiH3Properties.sidecars}}
          image: "{{ .baseRepo }}/{{ .images.nodeDriverRegistrar.image }}:{{ .images.nodeDriverRegistrar.tag }}"
          {{- end}}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-h3 /registration/csi-h3-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path={{ $csiH3Properties.sidecars.kubeletPath }}/plugins/csi-h3/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: h3
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: "{{ $csiH3Properties.baseRepo }}/{{ $csiH3Properties.csih3.image }}:{{ $csiH3Properties.csih3.tag }}"
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          # imagePullPolicy: "Always"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "mount -t fuse.h3fuse | while read -r mount; do umount $(echo $mount | awk '{print $3}') ; done"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: {{ $csiH3Properties.sidecars.kubeletPath }}/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: plugin-dir
          hostPath:
            path: {{ $csiH3Properties.sidecars.kubeletPath }}/plugins/csi-h3
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: {{ $csiH3Properties.sidecars.kubeletPath }}/pods
            type: Directory
        - hostPath:
            path: {{ $csiH3Properties.sidecars.kubeletPath }}/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
